# Generated by Django 3.0.1 on 2019-12-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0002_auto_20191223_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
