# Generated by Django 3.0.1 on 2020-01-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0005_auto_20200102_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
