# Generated by Django 3.0.1 on 2020-01-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0009_auto_20200103_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
