# Generated by Django 3.0.1 on 2020-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0010_auto_20200106_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['user'], 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_added', 'name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsamount',
            options={'verbose_name_plural': 'Products Amounts'},
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'verbose_name_plural': 'Retailers'},
        ),
        migrations.AddField(
            model_name='basket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'opened'), (1, 'paid'), (2, 'shiped'), (3, 'closed'), (4, 'cancelled'), (5, 'returned')], default=0),
        ),
    ]
