# Generated by Django 3.0.1 on 2020-01-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0011_auto_20200121_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='cost',
        ),
    ]
