# Generated by Django 3.0.1 on 2020-01-22 13:36

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0013_auto_20200121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'opened'), (1, 'paid'), (2, 'shiped'), (3, 'closed'), (4, 'cancelled'), (5, 'returned')], default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='productsamount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
