# Generated by Django 3.0.1 on 2020-02-03 21:25

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0014_auto_20200122_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsamount',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'opened'), (1, 'paid'), (2, 'shipped'), (3, 'closed'), (4, 'cancelled'), (5, 'returned')], default=0, protected=True),
        ),
    ]
