# Generated by Django 3.0.1 on 2020-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0015_auto_20200203_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsamount',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
