# Generated by Django 3.0.1 on 2020-02-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0016_productsamount_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsamount',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
