# Generated by Django 3.0.1 on 2020-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0017_auto_20200218_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsamount',
            name='date_created',
        ),
        migrations.AddField(
            model_name='basket',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
