# Generated by Django 3.0.1 on 2020-02-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0019_auto_20200225_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='paid',
        ),
    ]
