# Generated by Django 3.0.1 on 2020-02-27 20:57

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0020_remove_basket_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'opened'), (1, 'paid'), (2, 'shipped'), (3, 'closed'), (4, 'returned')], default=0),
        ),
    ]
