# Generated by Django 3.0.1 on 2020-03-03 14:52

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ewardrobe_app', '0021_auto_20200227_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'opened'), (1, 'paid'), (2, 'shipped'), (3, 'closed'), (4, 'returned')], default=0, protected=True),
        ),
    ]
